import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {spawnSync} from 'node:child_process';
import {reviewReadiness,reportDraft,emptyState,atomicJson,recordReview,prepareReportDraft} from '../scripts/review-core.mjs';
const id=n=>n.toString(16).padStart(32,'0');
function fixture(){return {id:id(9),fingerprint:'fp',curatorName:'Curator',bountyName:'News',space:'crypto',bountyId:id(8),spec:{spaceId:id(7)},family:'routine',kind:'news',caseKey:'2026-10-02',proposalIds:[id(6)],proposalRefs:{[id(6)]:{spaceId:id(7)}},itemIds:[id(1),id(2)],review:{fingerprint:'fp',outcome:'needs_correction',checkedAt:'2026-10-04T12:00:00Z',findings:[],coverage:[{itemId:id(1),outcome:'unresolved',evidence:['Copy audit limit'],selection:{outcome:'qualifies',evidence:['Official announcement and distinct event']}},{itemId:id(2),outcome:'does_not_meet_requirements',evidence:['Earlier submitted same event'],selection:{outcome:'does_not_qualify',evidence:['Verified duplicate']}}]}};}
test('resolved event selection permits copy-audit limits and a correction recommendation',()=>{const c=fixture();assert.equal(reviewReadiness(c).complete,true);assert.equal(reportDraft(c).readiness.complete,true);c.review.scoring={rate:10,weekly:{priorPoints:null}};assert.equal(reviewReadiness(c).complete,true);});
test('missing, unsupported and pending item decisions prevent final reporting',()=>{const c=fixture();delete c.review.coverage[0].selection;assert.equal(reviewReadiness(c).complete,false);c.review.coverage[0].selection={outcome:'unresolved',evidence:['Investigation']};assert.equal(reviewReadiness(c).complete,false);c.review.coverage[0].selection={outcome:'qualifies',evidence:[]};assert.equal(reviewReadiness(c).complete,false);});
test('material requirement blockers and stale revisions cannot be hidden by accepted item counts',()=>{const c=fixture();c.review.decisionGaps=['Resolve eligibility'];assert.equal(reviewReadiness(c).complete,false);delete c.review.decisionGaps;c.review.fingerprint='stale';assert.equal(reviewReadiness(c).complete,false);c.review.fingerprint='fp';c.review.outcome='unresolved';assert.equal(reviewReadiness(c).complete,false);});
test('bespoke packages require every item decision without importing news eligibility',()=>{const c=fixture();c.family='bespoke';c.kind='organize-claims';for(const row of c.review.coverage){delete row.selection;row.outcome='needs_correction';}assert.equal(reviewReadiness(c).complete,true);c.review.coverage[0].outcome='unresolved';assert.equal(reviewReadiness(c).complete,false);});
test('reports runner keeps unfinished cases in investigation queue and preserves previous receipts',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'review-completion-')),state=emptyState(),ready=fixture(),pending=fixture();pending.id=id(10);pending.review.coverage[0].selection.outcome='unresolved';pending.delivery={status:'verified',reportId:id(11),receipt:{url:'https://example.org/prior'}};state.cases[ready.id]=ready;state.cases[pending.id]=pending;atomicJson(path.join(dir,'state','state.json'),state);const out=path.join(dir,'out');const run=spawnSync(process.execPath,[new URL('../scripts/review.mjs',import.meta.url).pathname,'reports','--state',path.join(dir,'state'),'--out',out],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);const receipt=JSON.parse(fs.readFileSync(path.join(out,'workflow-status.json')));assert.equal(receipt.drafts.length,1);assert.equal(receipt.investigationNeeded[0].caseId,pending.id);assert.equal(fs.existsSync(path.join(out,pending.id+'.json')),false);const saved=JSON.parse(fs.readFileSync(path.join(dir,'state','state.json')));assert.deepEqual(saved.cases[pending.id].delivery,pending.delivery);});

test('recorded incomplete decisions remain queued and cannot mark a final draft ready',()=>{const c=fixture(),state=emptyState();state.cases[c.id]=c;const r={...c.review,caseId:c.id,requirements:[{criterion:'selection',outcome:'meets_requirements',evidence:['Bounty requirement']}]};r.coverage[0].selection.outcome='unresolved';recordReview(state,r);assert.equal(c.status,'review_unresolved');assert.throws(()=>prepareReportDraft(c,'unused.json'),/needs investigation/);r.coverage[0].selection.outcome='qualifies';recordReview(state,r);assert.equal(c.status,'reviewed');assert.equal(prepareReportDraft(c,'unused.json').draft.readiness.complete,true);});
