import {test} from 'node:test';
import assert from 'node:assert/strict';
import {editorSummary,editorSummaryMarkdown,reportDraft,recordReview,emptyState} from '../scripts/review-core.mjs';
const id=n=>n.toString(16).padStart(32,'0');
function fixture(){return {id:id(9),fingerprint:'fp',family:'routine',kind:'news',curatorName:'Fixture curator ',bountyName:'News',space:'crypto',bountyId:id(8),spec:{spaceId:id(7)},caseKey:'2026-10-02',proposalIds:[id(6)],proposalRefs:{[id(6)]:{spaceId:id(7)}},itemIds:[id(1),id(2),id(3)],review:{fingerprint:'fp',outcome:'needs_correction',checkedAt:'2026-10-03T23:40:00Z',findings:[],coverage:[{itemId:id(1),itemName:'Copy correction on qualifying event',outcome:'needs_correction',selection:{outcome:'qualifies',evidence:['Event passes']}},{itemId:id(2),itemName:'Earlier duplicate',selection:{outcome:'does_not_qualify',evidence:['Earlier event']}},{itemId:id(3),itemName:'Pending source'}],scoring:{rate:10,ruleSource:'PRIVATE_RULE_SENTINEL',weekly:{limit:250,priorPoints:null},monthly:{limit:1000,priorPoints:null}}}};}
test('independent selection credits a qualifying event despite copy correction; unknown checks are not rejected',()=>{const c=fixture(),s=editorSummary(c);assert.deepEqual(s.counts,{accepted:1,rejected:1,unresolved:1});assert.equal(s.pointsBeforeCaps,10);assert.equal(s.pointsAfterCaps,null);assert.equal(s.decisionStatus,'review_recommendation');assert.throws(()=>editorSummaryMarkdown(s),/Finish unresolved/);});
test('verified prior credit applies weekly and monthly headroom without counting the case twice',()=>{const c=fixture();c.review.scoring.weekly={limit:250,priorPoints:245,period:'W40',evidence:['ledger net of case']};c.review.scoring.monthly={limit:1000,priorPoints:998,period:'2026-10',evidence:['ledger net of case']};assert.equal(editorSummary(c).pointsAfterCaps,2);assert.equal(editorSummary(c).pointsAfterCaps,2);c.review.scoring.monthly.priorPoints=1100;assert.equal(editorSummary(c).pointsAfterCaps,0);});
test('repeated item IDs do not increase credit, bespoke and stale cases cannot silently receive routine scores',()=>{const c=fixture();c.itemIds.push(id(1));assert.equal(editorSummary(c).totalItems,3);assert.equal(editorSummary(c).pointsBeforeCaps,10);c.family='bespoke';assert.equal(editorSummary(c),null);c.family='routine';c.review.fingerprint='stale';assert.throws(()=>editorSummary(c),/current/);});
test('unknown rate gives no invented award; rejected-only cases have zero points',()=>{const c=fixture();delete c.review.scoring;assert.equal(editorSummary(c).pointsBeforeCaps,null);c.review.scoring={rate:10,ruleSource:'rule'};for(const row of c.review.coverage)row.selection={outcome:'does_not_qualify',evidence:['Failure']};assert.equal(editorSummary(c).pointsAfterCaps,0);});
test('editor tally and point rule never enter recipient Markdown; review date uses UTC',()=>{const c=fixture();c.review.coverage[2].selection={outcome:'qualifies',evidence:['Verified event']};const s=editorSummary(c),d=reportDraft(c);assert.ok(editorSummaryMarkdown(s).includes('PRIVATE_RULE_SENTINEL'));assert.equal(d.markdown.includes('PRIVATE_RULE_SENTINEL'),false);assert.equal(d.markdown.includes('Points before caps'),false);assert.match(d.markdown,/3 October 2026/);assert.equal(d.markdown.includes('4 October 2026'),false);});
test('recording rejects unsupported selection and invented known cap usage',()=>{const c=fixture(),state=emptyState();state.cases[c.id]=c;const review={...c.review,caseId:c.id,coverage:c.review.coverage.map(r=>({...r,outcome:'unresolved',evidence:['snapshot']})),requirements:[{outcome:'unresolved',evidence:['criterion']}]};review.coverage[0].selection.evidence=[];assert.throws(()=>recordReview(state,review),/Selection/);review.coverage[0].selection.evidence=['event'];review.scoring.weekly.priorPoints=0;assert.throws(()=>recordReview(state,review),/ledger/);});
